---
title: "Getting started with Testcontainers for Go"
date: 2023-05-26T09:39:58+05:30
draft: false
description: This guide will explain how to get started with Testcontainers for Go demonstrating how to use PostgreSQL database for testing.
repo: https://github.com/testcontainers/tc-guide-getting-started-with-testcontainers-for-go
languages:
  - Go
tags:
  - postgresql
---
:toc:
:toclevels: 2
:codebase: https://raw.githubusercontent.com/testcontainers/tc-guide-getting-started-with-testcontainers-for-go/main

In this guide, you will learn how to

* Create a Go application with modules support.
* Implement a Repository to manage customers data in PostgreSQL database using pgx driver.
* Test the database interactions using testcontainers-go.

== Prerequisites
* Go 1.19+
* Your favorite IDE(VS Code, GoLand)
* A Docker environment supported by Testcontainers https://golang.testcontainers.org/system_requirements/

== What we are going to achieve in this guide
We are going to create a Go project and implement a Repository to save and retrieve the customer details
from a PostgreSQL database. Then we will test this repository using the testcontainers-go postgres module.

== Getting Started
Let's start with creating a Go project.

[source,shell]
----
$ mkdir testcontainers-go-demo
$ cd testcontainers-go-demo
$ go mod init github.com/testcontainers/testcontainers-go-demo
----

We are going to use the https://github.com/jackc/pgx[jackc/pgx] PostgreSQL Driver to interact with the Postgres database
and the *testcontainers-go* https://golang.testcontainers.org/modules/postgres/[postgres module]
to spin up a Postgres docker instance for testing.
Also, we are going to use https://github.com/stretchr/testify[testify] for running multiple tests as a suite and for writing assertions.

[NOTE]
If you are new to Testcontainers, then please visit https://testcontainers.com/getting-started/[Testcontainers Getting Started] page
to learn more about Testcontainers and the benefits of using it.

Let's install these dependencies.

[source,shell]
----
$ go get github.com/jackc/pgx/v5
$ go get github.com/testcontainers/testcontainers-go
$ go get github.com/testcontainers/testcontainers-go/modules/postgres
$ go get github.com/stretchr/testify
----

After installing these dependencies, your `go.mod` file should look like this:

[source,go]
----
module github.com/testcontainers/testcontainers-go-demo

go 1.19

require (
   github.com/jackc/pgx/v5 v5.3.1
   github.com/stretchr/testify v1.8.3
   github.com/testcontainers/testcontainers-go v0.20.1
   github.com/testcontainers/testcontainers-go/modules/postgres v0.20.1
)

require (
   // indirect dependencies here
)
----

== Create Customer struct

First, let us start with creating a `types.go` file in `customer` package and
define the `Customer` struct to model the customer details as follows:

[source,go]
----
include::{codebase}/customer/types.go[]
----

== Create Repository
Next, create `customer/repo.go` file, define the `Repository` struct and then
add methods to create a new customer and get a customer by email as follows:

[source,go]
----
include::{codebase}/customer/repo.go[]
----

Let's understand what is going on here:

* We have defined a `Repository` struct with a field of type `*pgc.Conn` which will be used for performing database operations.
* We have defined a helper function `NewRepository(connStr)` that takes a database connection string and initializes `Repository`.
* Then we have implemented `CreateCustomer()` and `GetCustomerByEmail()` methods on the `Repository` receiver.

== Write test for Repository using testcontainers-go

We have our `Repository` implementation ready, but for testing we need a PostgreSQL database.
We can use *testcontainers-go* to spin up a Postgres database in a Docker container and run our tests
connecting to that database.

In real applications we might use some database migration tool, but for this guide let us use a simple script to initialize our database.

Create a `testdata/init-db.sql` file to create CUSTOMERS table and insert the sample data as follows:

[source,sql]
----
include::{codebase}/testdata/init-db.sql[]
----

The *testcontainers-go* library provides the generic *Container* abstraction that can be used to run
any containerised service. To further simplify, testcontainers-go provides technology specific modules
that will reduce the boilerplate and also provides a functional options pattern to easily construct
the container instance.

For example, PostgresContainer provides `WithImage()`, `WithDatabase()`, `WithUsername()`, `WithPassword()` etc functions
to set various properties of Postgres containers easily.

Now, let's create the `customer/repo_test.go` file and implement the test as follows:

[source,go]
----
include::{codebase}/customer/repo_test.go[]
----

Let's understand what is going on here:

* We have created an instance of `PostgresContainer` by specifying the Docker image `postgres:15.3-alpine`, from which the container needs to be created.
* We have configured the initialization scripts using `WithInitScripts(...)` so that after the database starts, the CUSTOMERS table will be created and sample data will be inserted.
* Next, we have specified the username, password and database name for the Postgres container.
* We have configured the `WaitStrategy` that will help to determine whether the Postgres container is fully ready to use or not.
* Then, we have defined the test cleanup function using `t.Cleanup(...)` so that at the end of the test the Postgres container will be removed.
* Next, we obtained the database `ConnectionString` from `PostgresContainer` and initialized `Repository`.
* Then, we have created a new customer with the email `henry@gmail.com` and verified that a customer with the email `henry@gmail.com` exists in our database.

== Reusing the containers and running multiple tests as a suite

In the previous section, we saw how to spin up a Postgres Docker container for a single test.
But usually we might have multiple tests in a single file, and we may want to reuse
the same Postgres Docker container for all the tests in that file.

We can use https://pkg.go.dev/github.com/stretchr/testify/suite[testify suite] package to implement
common test setup and teardown actions.

First, let us extract `PostgresContainer` creation logic into a separate file called `testhelpers/containers.go`.

[source,go]
----
include::{codebase}/testhelpers/containers.go[]
----

In `containers.go`, we have defined `PostgresContainer` struct which extends testcontainers-go `PostgresContainer` struct
to provide easy access to `ConnectionString` and created `CreatePostgresContainer()` function
to instantiate `PostgresContainer`.

Now, let's create `customer/repo_suite_test.go` file and implement tests for creating a new customer and
getting customer by email by using testify suite package as follows:

[source,go]
----
include::{codebase}/customer/repo_suite_test.go[]
----

Let's understand what is going on here:

* We have created `CustomerRepoTestSuite` by extending `suite.Suite` struct and added fields which will be used across multiple tests in that suite.
* In the `SetupSuite()` function which will be executed only once before executing the tests, we have created `PostgresContainer` and initialized `Repository`.
* In `TearDownSuite()` function which will be executed only once after all the tests in that suite are executed, we are terminating the container which will destroy the Postgres Docker container.
* Next, we have created the tests `TestCreateCustomer()` and `TestGetCustomerByEmail()` as receiver functions on the suite.
* Finally, we have created the test function `TestCustomerRepoTestSuite(t *testing.T)` which will run the test suite when we execute the tests using `go test`.

[TIP]
For the purpose of this guide, we are not resetting the data in the database.
But it is a good practice to reset the database in a known state before running any test.

== Run tests

You can run all the tests using `go test ./...` and optionally add the flag "-v" for displaying verbose output.

[source,shell]
----
$ go test -v ./...

=== RUN   TestCustomerRepoTestSuite
...
...
2023/06/13 09:27:11 🐳 Creating container for image docker.io/testcontainers/ryuk:0.4.0
2023/06/13 09:27:11 ✅ Container created: 2881f4e311a2
2023/06/13 09:27:11 🐳 Starting container: 2881f4e311a2
2023/06/13 09:27:12 🚧 Waiting for container id 2881f4e311a2 image: docker.io/testcontainers/ryuk:0.4.0
2023/06/13 09:27:12 ✅ Container started: 2881f4e311a2
2023/06/13 09:27:12 🐳 Creating container for image postgres:15.3-alpine
2023/06/13 09:27:12 ✅ Container created: a98029633d02
2023/06/13 09:27:12 🐳 Starting container: a98029633d02
2023/06/13 09:27:13 🚧 Waiting for container id a98029633d02 image: postgres:15.3-alpine
2023/06/13 09:27:14 ✅ Container started: a98029633d02
=== RUN   TestCustomerRepoTestSuite/TestCreateCustomer
=== RUN   TestCustomerRepoTestSuite/TestGetCustomerByEmail
2023/06/13 09:27:14 🐳 Terminating container: a98029633d02
2023/06/13 09:27:15 🚫 Container terminated: a98029633d02
--- PASS: TestCustomerRepoTestSuite (3.66s)
    --- PASS: TestCustomerRepoTestSuite/TestCreateCustomer (0.00s)
    --- PASS: TestCustomerRepoTestSuite/TestGetCustomerByEmail (0.00s)
=== RUN   TestCustomerRepository
2023/06/13 09:27:15 🐳 Creating container for image postgres:15.3-alpine
2023/06/13 09:27:15 ✅ Container created: fcf4241a61ab
2023/06/13 09:27:15 🐳 Starting container: fcf4241a61ab
2023/06/13 09:27:15 🚧 Waiting for container id fcf4241a61ab image: postgres:15.3-alpine
2023/06/13 09:27:16 ✅ Container started: fcf4241a61ab
2023/06/13 09:27:16 🐳 Terminating container: fcf4241a61ab
2023/06/13 09:27:17 🚫 Container terminated: fcf4241a61ab
--- PASS: TestCustomerRepository (1.94s)
PASS
ok  	github.com/testcontainers/testcontainers-go-demo/customer	6.177s
?   	github.com/testcontainers/testcontainers-go-demo/testhelpers	[no test files]
----

You should see two Postgres docker containers automatically started:
one for the suite and its two tests, and the other for the initial test we created,
and all those tests should PASS.
You can also notice that after tests are executed, the containers are stopped and removed automatically.

== Summary
The Testcontainers for Go library helped us to write integration tests by using the same type of database,
Postgres, that we use in production as opposed to using mocks.
As we are not using mocks and talking to the real services, we are free to do any code refactoring
and still ensure that the application is working as expected.

To learn more about Testcontainers visit http://testcontainers.com

== Further Reading
* https://golang.testcontainers.org/
* https://golang.testcontainers.org/quickstart/
* https://golang.testcontainers.org/modules/postgres/
* https://testcontainers.com/modules/

